# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a584fd28cd63a66d60fb6fe599f5c747"
application_url = "https://az-punishment-handmade-quantity.trycloudflare.com"
embedded = true
name = "Product Builder Pro"
handle = "product-builder-pro"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://az-punishment-handmade-quantity.trycloudflare.com/auth/callback",
  "https://az-punishment-handmade-quantity.trycloudflare.com/auth/shopify/callback",
  "https://az-punishment-handmade-quantity.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "best-foote-forward-development.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
